spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testpgsql
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
mybatis-flex:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
